### ISSUE TITLE
[Cryptomator] Silent installation shows dependency installation dialog

### ISSUE THREAD

**Issue by scowalt** [scowalt/chocolatey-packages#22]
http://disq.us/p/28bhj1m

**Comment by Laezylion** [comment]
Hello Scott !

I just found another old package on chocolatey, that installs the dokany in version 1.3 

 https://chocolatey.org/packages/dokany

But this package is old : version 1.4 of dokany is out and the owner looks like not responding anymore.

Would it be possible to take the package on your own to update it ?

**Comment by scowalt** [comment]
Hey Laezylion, I'm not willing to take ownership of that package. (To be honest, I don't even use Cryptomator anymore, I just keep the package updated as a service to the community)

It looks like there's already a separate issue on Github to address this - https://github.com/bcurran3/ChocolateyPackages/issues/188

Here's a reference to the chocolatey package takeover process too - https://docs.chocolatey.org/en-us/community-repository/maintainers/package-maintainer-handover
